### ISSUE TITLE
GC Data Analysis

### ISSUE THREAD

**Issue by mwang87** [mwang87/MassSpec-Coronavirus-Project-Docs#2]
ftp://massive.ucsd.edu/MSV000081891/updates/2020-03-22_alchemistmatt_9f32d6a1/peak/Peak_List_Files

- [x] Metadata - includes time point, condition
- [x] Feature Detection with MSHub
- [x] Identification/Networking
- [x] Updated metabolomics page 

The manuscript is here https://msystems.asm.org/content/1/3/e00043-16

**Comment by mwang87** [comment]
Put metadata here: 

https://github.com/mwang87/MassSpec-Coronavirus-Project-Docs/tree/master/docs/data

**Comment by mwang87** [comment]
@abauermeister will look for similar datasets to MSV000081891 on 

https://massive.ucsd.edu/ProteoSAFe/corona-mass-kb-datasets.jsp#%7B%22query%22%3A%7B%7D%2C%22table_sort_history%22%3A%22createdMillis_dsc%22%2C%22keywords_input%22%3A%22CoronaMassKB%22%7D

And make metadata for it.

**Comment by aaksenov1** [comment]
Deconvolution (ran successfully):
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=acba5743480040ea87bbcd4d41be168e
Library search w/metadata:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=988c86e75bc74efc81115cd08204e9e5

**Comment by abauermeister** [comment]
I added two more metadata for "Primary human airway epithelial cells metabolome response to an icMERS coronavirus". There are other GC-MS data sets for coronavirus, like "Primary human fibroblasts...", "mouse lung...", among others. Are we also interested in those data sets?

**Comment by mwang87** [comment]
That's great. Could we possible merge these metadata into one file, so then we can analyze them all together, I think the experimental design was that they were biological replicates. Lets address this data first then we can move on to those others

**Comment by aaksenov1** [comment]
Send me the full metadata and I will relaunch the search

**Comment by abauermeister** [comment]
Ok, I'll merge those 3 metadatas for epithelial cells. Just one sec.

**Comment by abauermeister** [comment]
@aaksenov1 the merged metadata was uploaded. Let me know if it worked.

**Comment by abauermeister** [comment]
@mwang87 , what do you mean with your reactions? Positive and negative at the same time?! I am confuse...hehe!!

**Comment by aaksenov1** [comment]
Library search with updated metadata:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=7f560f91c9b143c98c4013bbbd321df7

**Comment by mwang87** [comment]
@aaksenov1 I don't think this includes all datasets. There were CDF files from 3 datasets that @abauermeister found.

**Comment by aaksenov1** [comment]
For the MSV000081889, MSV000081890 they only have .D so we need to ask them for cdf again.

**Comment by aaksenov1** [comment]
Jobs for combined MSV000081889, MSV000081890 and MSV000081891
Deconvolution:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c86fe7fc666d4d9b84e5f4f7ae4be03a
Library search:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=632d7e1c98994d71bce1d5f95b7dfd19

**Comment by mwang87** [comment]
Closing issue. Now we'll start doing the analysis given this metadata.
